version: '3.7'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${STOCK_TABLE}
      MYSQL_USER: ${STOCK_USER}  
      MYSQL_PASSWORD: ${STOCK_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${STOCK_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysqlinstance:/var/lib/mysql
  # back:
  #   build: "./back"
  #   volumes:
  #     - ./back:/app
  #   environment:
  #     MYSQL_DATABASE: ${STOCK_TABLE}
  #     MYSQL_USER: ${STOCK_USER} 
  #     MYSQL_PASSWORD: ${STOCK_PASSWORD}
  #     DJANGO_SECRET_PHRASE: ${SECRET_PHRASE}
  #   command: python manage.py runserver 0.0.0.0:5000
  #   ports:
  #   - "5000:5000"
  #   depends_on:
  #     - db
  # front:
  #   build: "./front"
  #   command: npm start
  #   volumes:
  #     - ./front:/app
  #   ports:
  #     - "80:80"
  #     - "3000:3000"
  scrap:
    build: "./scraper"
    volumes:
      - ./scraper:/app
    environment:
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      EMAIL_PORT: ${EMAIL_PORT}
    ports:
      - ${EMAIL_PORT}:${EMAIL_PORT}
volumes: 
  mysqlinstance:
